spring:
  datasource:
    username: root
    password: kuang123
    url: jdbc:mysql://127.0.0.1:3306/demo
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.demo.studentmanage.model